### PR TITLE
Rename forward so it works with mf

### PR DESCRIPTION
**Pull request by Pernilleww**

### CODE REVIEW

**Comment by simeneide** [comment]
Hi @Pernilleww,
great find and thank you for your contribution :)

The repo is using the nbdev framework, so you only need to change the ipynb file manually. Then you run some nbdev commands to build the library. You can read more here: https://github.com/finn-no/recsys_slates_dataset/blob/main/CONTRIBUTING.md

But for TL/DR :
1. change the ipynb file (as you have already done)
2. make sure nbdev is installed `pip install nbdev`
3. run `nbdev_build_lib && nbdev_build_docs`. This will build the python files and any documenation changes needed.
4. Commit the changes (have a look to see that all changes are relevant)
5. Done :)

**Comment by Pernilleww** [comment]
image

Hm I get this error when I try to run ``nbdev_build_lib && nbdev_build_docs``

**Comment by simeneide** [comment]
Hm, can you try to do the following:
- revert the changes you did in `lightning_helper.py` - the .py file is automatically generated from the ipynb one.
- Upgrade nbdev to the latest version (if not already latest)
- run the two commands separately so we can debug what is happening.

**Comment by Pernilleww** [comment]
It fails when I run nbdev_build_docs, and in docs/lightning_helper.html I get this error:

`<div class="output_wrapper">
<div class="output">

<div class="output_area">

<div class="output_subarea output_stream output_stderr output_text">
<pre>c:\users\perni\appdata\local\programs\python\python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools&#39; objects directly or at least import Setuptools first.
  warnings.warn(
</pre>
</div>
</div>

</div>
</div>`

I have the latest nbdev version and use Python 3.10.0. I think it fails due to the character "almost equal to", but I am not sure how to fix this.

**Comment by simeneide** [comment]
Its hard to debug this, but I made the easy way out and created a separate PR (https://github.com/finn-no/recsys_slates_dataset/pull/16) with the same change. Ill add you as reviewer.

Also, I did not remove the `t_rec` argument, as this is needed for autoregressive models.

**Pull request closed without merging**
